export const ADD_MEMBERSHIP_USER = "ADD_MEMBERSHIP_USER";
export const ADD_MEMBERSHIP_USERS = "ADD_MEMBERSHIP_USERS";
export const SET_MEMBERSHIP_USER_LOADING = "SET_MEMBERSHIP_USER_LOADING";
export const SET_MEMBERSHIP_USER_REQUEST = "SET_MEMBERSHIP_USER_REQUEST";
export const SET_MEMBERSHIP_USER_IDS = "SET_MEMBERSHIP_USER_IDS";
export const RESET_MEMBERSHIP_USER = "RESET_MEMBERSHIP_USER";
